<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FS4CIQU" failures="1" tests="8" name="org.testNG.expriments.Test9Groups" time="0.015" errors="0" timestamp="28 Feb 2022 16:32:01 GMT" skipped="3">
  <testcase classname="org.testNG.expriments.Test9Groups" name="test91" time="0.007"/>
  <testcase classname="org.testNG.expriments.Test9Groups" name="test92" time="0.000">
    <skipped/>
  </testcase> <!-- test92 -->
  <testcase classname="org.testNG.expriments.Test9Groups" name="test92" time="0.002">
    <skipped/>
  </testcase> <!-- test92 -->
  <testcase classname="org.testNG.expriments.Test9Groups" name="test92" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.testNG.expriments.Test9Groups.test92(Test9Groups.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test92 -->
  <testcase classname="org.testNG.expriments.Test9Groups" name="test95" time="0.000"/>
  <testcase classname="org.testNG.expriments.Test9Groups" name="test92" time="0.004">
    <skipped/>
  </testcase> <!-- test92 -->
  <testcase classname="org.testNG.expriments.Test9Groups" name="test94" time="0.001"/>
  <testcase classname="org.testNG.expriments.Test9Groups" name="test93" time="0.000"/>
</testsuite> <!-- org.testNG.expriments.Test9Groups -->
